// Semilla curada de la guía. Texto NUESTRO, con la voz de IDENTIDAD.md: datos y
// no adjetivos, un consejo útil por lugar, de tú a tú. `busqueda` es lo que se
// le pide a Google Places para cruzar los datos; `commons` lo que se busca en
// Wikimedia para fotos libres (si falta, se usa el nombre).
import type { Categoria } from '../lib/guia';

export interface Semilla {
  nombre: string; categoria: Categoria; busqueda: string; commons?: string;
  descripcion: string; consejo: string; mejorMomento?: string; duracion?: string; costo?: string;
  instagram?: string; web?: string; destacado?: boolean; municipio?: string;
  telefono?: string; direccion?: string; // para servicios que Google no tiene bien
  aliado?: boolean; // trato directo con nosotros: sello «Recomendado» y primero en su categoría
  categoriasExtra?: Categoria[]; // también aparece en estas categorías
}

export const LUGARES: Semilla[] = [
  // ── Playas ────────────────────────────────────────────────────────────────
  { nombre: 'Playa El Agua', categoria: 'playa', busqueda: 'Playa El Agua Isla de Margarita', commons: 'Playa El Agua Margarita', destacado: true, municipio: 'Antolín del Campo',
    descripcion: 'Cuatro kilómetros de arena y palmeras en la costa noreste: la playa más conocida de la isla. Tiene la fila más larga de restaurantes y toldos, y el mar es abierto, con oleaje que sube por la tarde.',
    consejo: 'El mar tiene corrientes en algunos tramos: quédate donde haya bañistas y salvavidas. Los toldos se negocian; pregunta el precio antes de sentarte.', mejorMomento: 'Mañana, hasta las 11', duracion: 'Medio día', costo: 'Gratis · toldo y sillas aparte' },
  { nombre: 'Playa Parguito', categoria: 'playa', busqueda: 'Playa Parguito Isla de Margarita', commons: 'Playa Parguito', destacado: true, municipio: 'Antolín del Campo',
    descripcion: 'Pegada a El Agua pero con carácter propio: es la playa de las olas y del surf, con ambiente joven y menos toldos. Arena gruesa y agua clara.',
    consejo: 'Si vas con niños chicos, mejor El Agua o Puerto Cruz: acá el oleaje es fuerte. Hay alquiler de tablas en la orilla.', mejorMomento: 'Tarde', duracion: '2–4 horas', costo: 'Gratis' },
  { nombre: 'Playa El Yaque', categoria: 'playa', busqueda: 'Playa El Yaque', commons: 'Playa El Yaque', destacado: true, municipio: 'Tubores',
    descripcion: 'Agua plana, poca profundidad y viento constante casi todas las tardes: por eso es uno de los lugares de referencia del mundo para kitesurf y windsurf. Está a 5 minutos del aeropuerto, con hoteles, escuelas y bares frente a la playa.',
    consejo: 'El viento arranca hacia el mediodía. Para bañarte tranquilo, mañana; para ver kites, de 1 a 5. Se puede cruzar en lancha a la isla de Coche desde acá.', mejorMomento: 'Tarde con viento', duracion: 'Medio día', costo: 'Gratis · clase de kite aparte' },
  { nombre: 'Playa Caribe', categoria: 'playa', busqueda: 'Playa Caribe Isla de Margarita', commons: 'Playa Caribe Margarita', municipio: 'Marcano',
    descripcion: 'En la costa norte, entre Juan Griego y Manzanillo. Arena clara, agua transparente y oleaje moderado. Es de las playas más limpias y menos ruidosas de la isla.',
    consejo: 'Hay pocos servicios: lleva agua y algo de comer. El acceso es fácil en carro y hay dónde estacionar.', mejorMomento: 'Mañana', duracion: 'Medio día', costo: 'Gratis' },
  { nombre: 'Playa Puerto Cruz', categoria: 'playa', busqueda: 'Playa Puerto Cruz Isla de Margarita', commons: 'Playa Puerto Cruz', municipio: 'Gómez',
    descripcion: 'Una bahía ancha y tranquila al norte, con arena fina y agua calma. Menos concurrida que El Agua y con servicios de sillas y toldos. Buena para familias.',
    consejo: 'Los fines de semana de temporada se llena a partir de las 11; entre semana la tienes casi para ti.', mejorMomento: 'Mañana', duracion: 'Medio día', costo: 'Gratis · toldo aparte' },
  { nombre: 'Playa Zaragoza', categoria: 'playa', busqueda: 'Playa Zaragoza Pedro González', commons: 'Playa Zaragoza Margarita', municipio: 'Gómez',
    descripcion: 'La playa del pueblo de Pedro González, con casas de colores frente al mar y una iglesia al fondo. Ambiente de pueblo de pescadores más que de resort.',
    consejo: 'Vale la pena caminar el malecón y comer pescado frito en los kioscos. Combínala con Puerto Cruz, que está a 5 minutos.', mejorMomento: 'Tarde', duracion: '2–3 horas', costo: 'Gratis' },
  { nombre: 'Playa Guacuco', categoria: 'playa', busqueda: 'Playa Guacuco', commons: 'Playa Guacuco', municipio: 'Arismendi',
    descripcion: 'Playa larga y abierta del este, a 15 minutos de Porlamar. Favorita de los margariteños los domingos: arena amplia, cocoteros y restaurantes de pescado.',
    consejo: 'El oleaje es moderado pero el fondo baja rápido. Prueba el pescado frito con arepitas dulces, que es lo típico acá.', mejorMomento: 'Mañana', duracion: 'Medio día', costo: 'Gratis' },
  { nombre: 'Playa Manzanillo', categoria: 'playa', busqueda: 'Playa Manzanillo Isla de Margarita', commons: 'Manzanillo Margarita', municipio: 'Marcano',
    descripcion: 'Bahía protegida en el extremo norte, con un pueblo de pescadores y agua calma. Es de las playas más fotografiadas por la vista desde el mirador de la bajada.',
    consejo: 'Para en el mirador antes de bajar: la vista de la bahía completa es la foto. Abajo hay pocos servicios.', mejorMomento: 'Atardecer', duracion: '2 horas', costo: 'Gratis' },
  { nombre: 'Playa Punta Arenas', categoria: 'playa', busqueda: 'Playa Punta Arenas Macanao', commons: 'Punta Arenas Macanao', municipio: 'Península de Macanao',
    descripcion: 'En la punta oeste de la península de Macanao, la parte más seca y despoblada de la isla. Agua calma y transparente, arena suave y muy poca gente. Hay kioscos de comida.',
    consejo: 'Son 50 minutos desde Porlamar por carretera solitaria: ve con el tanque lleno y de día. Es el mejor lugar de la isla para ver el atardecer.', mejorMomento: 'Atardecer', duracion: 'Día completo', costo: 'Gratis' },
  { nombre: 'Playa La Pared', categoria: 'playa', busqueda: 'Playa La Pared Macanao', commons: 'Playa La Pared Margarita', municipio: 'Península de Macanao',
    descripcion: 'Playa salvaje de Macanao entre acantilados, con oleaje fuerte y paisaje de desierto junto al mar. No es para bañarse: es para mirar.',
    consejo: 'No te metas al agua: hay corrientes. Es una parada de 20 minutos para la foto camino a Punta Arenas.', mejorMomento: 'Tarde', duracion: '30 minutos', costo: 'Gratis' },
  { nombre: 'Playa de Pampatar', categoria: 'playa', busqueda: 'Playa de Pampatar', commons: 'Pampatar bahía', municipio: 'Maneiro',
    descripcion: 'La bahía de Pampatar, con los botes de pescadores fondeados frente al castillo y la iglesia colonial. Agua calma; más para pasear que para pasar el día de playa.',
    consejo: 'Combina castillo, iglesia y una cerveza frente a los botes al atardecer. Los pescadores venden pescado fresco en la mañana.', mejorMomento: 'Atardecer', duracion: '2 horas', costo: 'Gratis' },

  // ── Historia ──────────────────────────────────────────────────────────────
  { nombre: 'Castillo de San Carlos de Borromeo', categoria: 'historia', busqueda: 'Castillo de San Carlos de Borromeo Pampatar', commons: 'Castillo San Carlos de Borromeo Pampatar', destacado: true, municipio: 'Maneiro',
    descripcion: 'Fortaleza española de 1684 frente a la bahía de Pampatar, la mejor conservada de la isla. Tiene cañones, un pequeño museo y vista completa de la bahía desde las murallas.',
    consejo: 'La entrada es barata y hay guías que explican en 20 minutos; vale la pena. Ve temprano: al sol del mediodía las murallas queman.', mejorMomento: 'Mañana o atardecer', duracion: '1 hora', costo: 'Entrada económica' },
  { nombre: 'Fortín de La Galera', categoria: 'historia', busqueda: 'Fortín de La Galera Juan Griego', commons: 'Fortín de la Galera Juan Griego', destacado: true, municipio: 'Marcano',
    descripcion: 'Fortín sobre un cerro en Juan Griego, escenario de una batalla de la independencia en 1817. Hoy es el punto clásico para ver el atardecer sobre la bahía, con la laguna de Los Mártires abajo.',
    consejo: 'Llega 40 minutos antes de que baje el sol; se llena. Estaciona abajo y sube caminando. Después, cena en el malecón de Juan Griego.', mejorMomento: 'Atardecer', duracion: '1 hora', costo: 'Gratis' },
  { nombre: 'Castillo de Santa Rosa', categoria: 'historia', busqueda: 'Castillo de Santa Rosa La Asunción', commons: 'Castillo de Santa Rosa La Asunción', municipio: 'Arismendi',
    descripcion: 'Fortaleza del siglo XVII sobre La Asunción, la capital del estado. Acá estuvo presa Luisa Cáceres de Arismendi, heroína de la independencia. Vista del valle y del cerro Copey.',
    consejo: 'Combínalo con la plaza Bolívar y la catedral de La Asunción, a 5 minutos caminando: es el casco colonial mejor conservado de la isla.', mejorMomento: 'Mañana', duracion: '1 hora', costo: 'Entrada económica' },
  { nombre: 'Basílica de Nuestra Señora del Valle', categoria: 'historia', busqueda: 'Basílica Menor Nuestra Señora del Valle Isla de Margarita', commons: 'Basílica Virgen del Valle', destacado: true, municipio: 'García',
    descripcion: 'El santuario de la Virgen del Valle, patrona de la isla y de los pescadores de todo el oriente venezolano. Iglesia de estilo neogótico en el pueblo de El Valle del Espíritu Santo, con un museo de ofrendas al lado.',
    consejo: 'El 8 de septiembre es la fiesta grande y llega gente de todo el país. Cualquier otro día se visita en calma; vístete con hombros cubiertos.', mejorMomento: 'Mañana', duracion: '1 hora', costo: 'Gratis' },
  { nombre: 'Fortín de La Caranta', categoria: 'historia', busqueda: 'Fortín de La Caranta Pampatar', commons: 'Fortín La Caranta', municipio: 'Maneiro',
    descripcion: 'Ruinas de un fortín del siglo XVII en el cerro que cierra la bahía de Pampatar por el sur. Poco visitado, con la mejor vista de Pampatar y Porlamar.',
    consejo: 'Se sube en carro hasta arriba. Sin servicios: es parada de 20 minutos para la vista.', mejorMomento: 'Atardecer', duracion: '30 minutos', costo: 'Gratis' },
  { nombre: 'Salinas de Pampatar', categoria: 'naturaleza', busqueda: 'Salinas de Pampatar', commons: 'Salinas de Pampatar', municipio: 'Maneiro',
    descripcion: 'Laguna salada en plena Pampatar donde todavía se extrae sal a mano. Según la época, el agua se pone rosada por las algas. Hay flamencos y otras aves.',
    consejo: 'Los mejores colores son con sol alto y la laguna con poca agua (temporada seca, de enero a mayo). Mira desde el borde: no se camina sobre la sal.', mejorMomento: 'Mediodía', duracion: '30 minutos', costo: 'Gratis' },
  { nombre: 'Faro de Punta Ballena', categoria: 'mirador', busqueda: 'Faro de Punta Ballena Pampatar', commons: 'Faro Punta Ballena Pampatar', municipio: 'Maneiro',
    descripcion: 'Faro sobre las rocas al final de Pampatar, con un paseo pavimentado y vista abierta al mar y a la bahía. Lugar de caminata al atardecer.',
    consejo: 'Ideal para caminar o trotar temprano o al caer el sol. Hay vendedores de helados y coco los fines de semana.', mejorMomento: 'Atardecer', duracion: '1 hora', costo: 'Gratis' },

  // ── Naturaleza ────────────────────────────────────────────────────────────
  { nombre: 'Parque Nacional Laguna de La Restinga', categoria: 'naturaleza', busqueda: 'Parque Nacional Laguna de La Restinga', commons: 'Laguna de La Restinga', destacado: true, municipio: 'Tubores',
    descripcion: 'Laguna de manglares que une las dos partes de la isla. Se recorre en lancha por canales con nombres (el Túnel del Amor, el Canal de la Serpiente) y se termina en una playa larguísima frente al mar abierto, con restaurantes de pescado.',
    consejo: 'El paseo en lancha se paga en el embarcadero y dura unos 40 minutos; acuerda el precio y la hora de regreso antes de salir. Repelente: hay mosquitos al amanecer y al atardecer.', mejorMomento: 'Mañana', duracion: 'Medio día', costo: 'Lancha por grupo · entrada al parque' },
  { nombre: 'Cerro El Copey', categoria: 'naturaleza', busqueda: 'Parque Nacional Cerro El Copey', commons: 'Cerro El Copey', municipio: 'Arismendi',
    descripcion: 'El punto más alto de la isla (930 m), parque nacional de bosque húmedo en medio de una isla seca. Se sube en carro por la carretera de La Sierra, con miradores hacia las dos costas.',
    consejo: 'Arriba hace fresco y hay nubes: lleva algo de manga larga. La carretera es angosta; ve despacio.', mejorMomento: 'Mañana despejada', duracion: '2–3 horas', costo: 'Gratis' },
  { nombre: 'Isla de Coche', categoria: 'actividad', busqueda: 'Playa la Punta Isla de Coche', commons: 'Isla de Coche', destacado: true, municipio: 'Villalba',
    descripcion: 'Isla pequeña al sur de Margarita, a 20–30 minutos en lancha desde El Yaque o en ferry desde Punta de Piedras. Playas de arena blanca, agua calma y viento: kitesurf, cuatrimotos y un día de playa sin multitudes.',
    consejo: 'El full day en lancha desde El Yaque suele incluir el traslado y a veces almuerzo; compara dos operadores. Lleva efectivo: en Coche hay pocos puntos de pago.', mejorMomento: 'Día completo', duracion: 'Día completo', costo: 'Excursión por persona' },
  { nombre: 'Isla de Cubagua', categoria: 'actividad', busqueda: 'Isla de Cubagua', commons: 'Cubagua', municipio: 'Tubores',
    descripcion: 'Isla desierta al sur, donde estuvo Nueva Cádiz, la primera ciudad española de Sudamérica (siglo XVI, hoy ruinas). Agua transparente, arena blanca y nada más: no hay pueblo ni servicios.',
    consejo: 'Solo se llega en excursión en lancha (desde El Yaque o Punta de Piedras). Todo lo que necesites va contigo: agua, comida, sombra.', mejorMomento: 'Día completo', duracion: 'Día completo', costo: 'Excursión por persona' },

  // ── Miradores ─────────────────────────────────────────────────────────────
  { nombre: 'Mirador La Sierra', categoria: 'mirador', busqueda: 'Mirador La Sierra Isla de Margarita', commons: 'La Sierra Margarita mirador', municipio: 'Arismendi',
    descripcion: 'En la carretera que sube al Copey, el mirador con la vista más amplia de la isla: el valle de La Asunción, Porlamar y el mar al fondo.',
    consejo: 'Los fines de semana hay puestos de comida y dulces criollos. Temprano en la mañana hay menos nubes.', mejorMomento: 'Mañana', duracion: '30 minutos', costo: 'Gratis' },
  { nombre: 'Mirador de Playa Manzanillo', categoria: 'mirador', busqueda: 'Mirador Playa Manzanillo', commons: 'Manzanillo Margarita', municipio: 'Marcano',
    descripcion: 'La curva de la carretera antes de bajar a Manzanillo, con la bahía completa, el pueblo y los botes abajo. La postal de la costa norte.',
    consejo: 'Parada de 10 minutos. Estaciona bien a un lado: la carretera es angosta.', mejorMomento: 'Atardecer', duracion: '15 minutos', costo: 'Gratis' },

  // ── Museos ────────────────────────────────────────────────────────────────
  { nombre: 'Museo Marino de Margarita', categoria: 'museo', busqueda: 'Museo Marino de Margarita Boca de Río', commons: 'Museo Marino de Margarita', municipio: 'Península de Macanao',
    descripcion: 'En Boca de Río, a la entrada de Macanao. Esqueletos de ballenas, peces vivos en acuarios, tortugas y una colección de especies del Caribe. Muy bueno para ir con niños.',
    consejo: 'Combínalo con La Restinga, que está a 10 minutos. El museo cierra al mediodía en algunas temporadas: confirma el horario abajo.', mejorMomento: 'Mañana', duracion: '1–2 horas', costo: 'Entrada económica' },
  { nombre: 'Museo de Arte Contemporáneo Francisco Narváez', categoria: 'museo', busqueda: 'Museo de Arte Contemporáneo Francisco Narváez Porlamar', commons: 'Museo Francisco Narváez Porlamar', municipio: 'Mariño',
    descripcion: 'En el centro de Porlamar, dedicado al escultor margariteño Francisco Narváez y a artistas venezolanos contemporáneos. Un espacio fresco y tranquilo para una hora fuera del sol.',
    consejo: 'Aprovecha para caminar el bulevar Guevara y la iglesia de San Nicolás, a dos cuadras.', mejorMomento: 'Mediodía (aire acondicionado)', duracion: '1 hora', costo: 'Gratis o entrada económica' },

  // ── Qué hacer ─────────────────────────────────────────────────────────────
  { nombre: 'Kitesurf y windsurf en El Yaque', categoria: 'aventura', busqueda: 'Margarita Kite El Yaque escuela kitesurf', commons: 'Kitesurf El Yaque', destacado: true, instagram: 'margaritakite', municipio: 'Tubores',
    descripcion: 'Aprender kite en El Yaque es más fácil que en casi cualquier otro lugar: el agua es plana y baja, y el viento entra casi todas las tardes. Hay varias escuelas con instructores certificados; un curso básico son unas 6–9 horas repartidas en 2–3 días.',
    consejo: 'Reserva la clase por Instagram o WhatsApp con un día de anticipación y pregunta si el equipo está incluido. Protector solar resistente al agua y lycra: el sol de la tarde pega fuerte.', mejorMomento: 'Tarde (1 a 5)', duracion: '2–3 horas por clase', costo: 'Curso por horas' },
  { nombre: 'Buceo y snorkel en Los Frailes', categoria: 'aventura', busqueda: 'Scuba Diving Margarita buceo', commons: 'Los Frailes Venezuela', destacado: true, instagram: 'scubadivingmargarita', municipio: 'Antolín del Campo',
    descripcion: 'Los Frailes son un archipiélago de islotes frente a la costa este, a unos 30 minutos en lancha. Agua transparente, arrecifes y cardúmenes: el mejor buceo y snorkel de la zona. Hay salidas de día completo con almuerzo, y minicursos para principiantes.',
    consejo: 'Confirma que el operador tenga equipo en buen estado y guía certificado. Si nunca buceaste, el bautizo en aguas calmas es la forma de probar sin certificación.', mejorMomento: 'Mañana (mar más calmo)', duracion: 'Día completo', costo: 'Salida por persona' },
  { nombre: 'Paseo en lancha por los manglares', categoria: 'actividad', busqueda: 'embarcadero La Restinga paseo en lancha', commons: 'Laguna de La Restinga manglar', municipio: 'Tubores',
    descripcion: 'Desde el embarcadero de La Restinga, lanchas de pescadores te llevan por los canales de manglar hasta la playa del parque. Se ven ostras pegadas a las raíces, aves y, con suerte, caballitos de mar.',
    consejo: 'El precio es por lancha (hasta 6–8 personas), no por persona: si van pocos, compartan. Pide que los dejen en la playa y los recojan a una hora fija.', mejorMomento: 'Mañana', duracion: '2–4 horas', costo: 'Lancha por grupo' },
  { nombre: 'Excursión a Coche y Cubagua en lancha', categoria: 'actividad', busqueda: 'paseo en lancha El Yaque Coche Cubagua', commons: 'Isla de Coche playa', web: 'https://tulanchaenmargarita.com.ve/', municipio: 'Tubores',
    descripcion: 'Full day en lancha o catamarán desde El Yaque: Coche, Cubagua o las dos, con paradas para nadar y snorkel. Es la excursión más pedida de la isla.',
    consejo: 'Pregunta qué incluye (almuerzo, bebidas, snorkel) y cuánta gente va en la lancha. Sal temprano: el mar está más calmo antes del mediodía.', mejorMomento: 'Salida a las 8–9', duracion: 'Día completo', costo: 'Excursión por persona' },
  { nombre: 'Kitesurf en la isla de Coche', categoria: 'aventura', busqueda: 'Coche Kite Isla de Coche', commons: 'Isla de Coche kitesurf', instagram: 'cochekite', municipio: 'Villalba',
    descripcion: 'Coche tiene el mismo viento que El Yaque con menos gente en el agua: escuelas y spots frente a hoteles de playa, para quien ya sabe o quiere aprender con calma.',
    consejo: 'Muchos hacen 2 días en El Yaque y 1 en Coche. Se puede ir y volver en el día en lancha.', mejorMomento: 'Tarde', duracion: 'Día completo', costo: 'Clase por horas' },

  // ── Con niños ─────────────────────────────────────────────────────────────
  { nombre: 'Waterland Mundo Marino', categoria: 'familia', busqueda: 'Waterland Mundo Marino Isla de Margarita', municipio: 'Maneiro',
    descripcion: 'Parque con shows de delfines y lobos marinos, y actividad de nado con delfines. Está en Pampatar, cerca de la zona hotelera.',
    consejo: 'Los shows tienen horarios fijos: revisa abajo y llega 20 minutos antes. El nado con delfines se reserva aparte y se llena en temporada.', mejorMomento: 'Mañana', duracion: '2–3 horas', costo: 'Entrada · nado aparte' },
  { nombre: 'Parque El Agua', categoria: 'familia', busqueda: 'Parque El Agua parque acuático Margarita', municipio: 'Antolín del Campo',
    descripcion: 'Parque acuático con toboganes, piscina de olas y río lento, en la vía a Playa El Agua. Un día completo para niños y adolescentes.',
    consejo: 'Lleva comida o compra adentro (afuera no hay mucho). Entre semana casi no hay cola en los toboganes.', mejorMomento: 'Día completo', duracion: 'Día completo', costo: 'Entrada por persona' },

  // ── Compras ───────────────────────────────────────────────────────────────
  { nombre: 'Centro Comercial Sambil Margarita', categoria: 'compras', busqueda: 'Sambil Margarita', municipio: 'Maneiro',
    descripcion: 'El centro comercial más grande de la isla, en Pampatar: tiendas, cine, feria de comida y supermercado. Aire acondicionado para las horas de más calor.',
    consejo: 'Es el lugar más fácil para cambiar o gastar dólares y pagar con tarjeta internacional. Los domingos por la tarde se llena.', mejorMomento: 'Tarde', duracion: '2–3 horas', costo: '—' },
  { nombre: 'Mercado de Conejeros', categoria: 'compras', busqueda: 'Mercado de Conejeros Porlamar', municipio: 'Mariño',
    descripcion: 'El mercado popular de Porlamar: pescado del día, frutas, quesos, ropa y artesanía a precios de la isla. Ruidoso, auténtico y barato.',
    consejo: 'Ve temprano (7–10), con efectivo en bolívares y sin joyas a la vista. Regatear es normal.', mejorMomento: 'Mañana temprano', duracion: '1–2 horas', costo: '—' },
  { nombre: 'Centro Comercial La Vela', categoria: 'compras', busqueda: 'Centro Comercial La Vela Margarita', municipio: 'Mariño',
    descripcion: 'Centro comercial abierto junto al mar entre Porlamar y Pampatar, con restaurantes, heladerías y tiendas. Más para pasear al atardecer que para comprar.',
    consejo: 'Buen plan de tarde-noche con niños: hay espacio para caminar y comer frente al mar.', mejorMomento: 'Atardecer', duracion: '2 horas', costo: '—' },
  // ── Alternativos (salieron de la búsqueda en Instagram: @margaritasecreta,
  //    @espartanostrekkingmgta, @nicomacanao; verificados en Google Places) ──
  { nombre: 'Laguna de Las Marites', categoria: 'naturaleza', busqueda: 'Monumento Natural Laguna de Las Marites', municipio: 'Mariño',
    descripcion: 'Monumento natural a 10 minutos de Porlamar, hacia Punta de Piedras: una laguna de manglares con aves (garzas, flamencos según la época) y canales que se recorren en lancha de pescadores. Es la versión chica y sin turismo de La Restinga.',
    consejo: 'Los lancheros están en el caserío de Las Marites; acuerda precio y tiempo antes de subir. Temprano hay más aves y menos calor.', mejorMomento: 'Amanecer', duracion: '2 horas', costo: 'Lancha por grupo' },
  { nombre: 'Cerro Matasiete', categoria: 'aventura', busqueda: 'Cerro Matasiete La Asunción', municipio: 'Arismendi', instagram: 'espartanostrekkingmgta',
    descripcion: 'Monumento natural sobre La Asunción, donde en 1817 se libró la batalla de Matasiete. Hoy es la caminata clásica de la isla: subida de 2 a 3 horas por sendero marcado, con vista de las dos costas desde arriba. Hay grupos de senderismo que organizan salidas los fines de semana.',
    consejo: 'Sal antes de las 7 de la mañana, con 2 litros de agua por persona y zapatos cerrados. Mejor en grupo: pregunta a Espartanos Trekking por la próxima salida.', mejorMomento: 'Amanecer', duracion: 'Medio día', costo: 'Gratis · salida guiada aparte' },
  { nombre: 'Playa El Tirano', categoria: 'playa', busqueda: 'Playa El Tirano Puerto Fermín', municipio: 'Antolín del Campo',
    descripcion: 'La playa del pueblo de Puerto Fermín, entre El Agua y Parguito pero con botes de pescadores en vez de toldos. Se come pescado del día en los kioscos frente al agua y se ve el mar sin música alta.',
    consejo: 'Ven a almorzar: el pescado sale del bote a la mesa. El nombre viene de Lope de Aguirre, «el Tirano», que desembarcó acá en 1561.', mejorMomento: 'Mediodía', duracion: '2–3 horas', costo: 'Gratis' },
  { nombre: 'Playa La Auyama', categoria: 'playa', busqueda: 'Playa La Auyama Macanao', municipio: 'Península de Macanao',
    descripcion: 'Playa de Macanao con acantilados de arcilla roja que caen al mar, arena clara y casi nadie. Paisaje de desierto y agua tranquila. Sin servicios.',
    consejo: 'Está en la carretera de la costa sur de Macanao, antes de Punta Arenas. Todo lo que necesites va contigo. Al atardecer los acantilados se ponen naranja.', mejorMomento: 'Atardecer', duracion: '2 horas', costo: 'Gratis' },
  { nombre: 'Boca de Pozo', categoria: 'historia', busqueda: 'Boca de Pozo Macanao plaza Bolívar', municipio: 'Península de Macanao',
    descripcion: 'La capital de Macanao: un pueblo de pescadores con plaza, iglesia y malecón, donde la península todavía vive del mar. Es la parada para entender la otra Margarita, la que no tiene hoteles.',
    consejo: 'Camina la plaza Bolívar y el malecón a la caída del sol, y compra empanadas en la esquina de la plaza. Combínalo con la laguna El Morro, a 5 minutos.', mejorMomento: 'Atardecer', duracion: '1 hora', costo: 'Gratis' },
  { nombre: 'Laguna El Morro', categoria: 'naturaleza', busqueda: 'Laguna El Morro Boca de Pozo', municipio: 'Península de Macanao',
    descripcion: 'Reserva natural junto a Boca de Pozo: una laguna costera con manglar, aves y un cerro (el Morro) desde donde se ve toda la costa sur de Macanao.',
    consejo: 'Repelente y sombrero. Es un paseo corto; la subida al Morro para la vista vale la pena si el día está despejado.', mejorMomento: 'Mañana', duracion: '1 hora', costo: 'Gratis' },
  { nombre: 'Playa Caracola', categoria: 'playa', busqueda: 'Playa Caracola Pampatar', municipio: 'Maneiro',
    descripcion: 'Playa urbana entre Pampatar y Porlamar, con agua calma, arena fina y edificios frente al mar. Cómoda para un rato de playa sin moverse de la ciudad.',
    consejo: 'Buena para el último día antes del vuelo o para bañarse temprano. Hay pocos toldos: lleva sombrilla.', mejorMomento: 'Mañana', duracion: '2 horas', costo: 'Gratis' },
  { nombre: 'Senderismo por los cerros de la isla', categoria: 'aventura', busqueda: 'Espartanos Trekking Margarita senderismo', municipio: 'Arismendi', instagram: 'espartanostrekkingmgta',
    descripcion: 'Margarita también se camina: Matasiete, el Copey, los cerros de Macanao y senderos al amanecer con vista a las dos costas. Hay grupos locales que salen los fines de semana, para principiantes y para quien ya camina.',
    consejo: 'Súmate a una salida organizada: conocen la ruta, el clima y la hora. Zapatos cerrados, gorra, agua y algo de comer. Nunca solo ni sin avisar.', mejorMomento: 'Amanecer', duracion: 'Medio día', costo: 'Salida por persona' },
  // ── Servicios (grupo «resolver»): lo que se necesita desde el apartamento.
  //    Descubiertos en Google Places e Instagram (@tucisternamargarita,
  //    @aguagraterol, @elabuelopachangueromgta, @alcostomgta, @farmaciaelcrucero.mgta). ──
  { nombre: 'Sigo Supermarket', categoria: 'supermercado', busqueda: 'Sigo Supermarket Costa Azul Porlamar', municipio: 'Mariño',
    descripcion: 'La cadena de supermercados de la isla, con varias sedes (Costa Azul, Sambil, Porlamar). Surtido completo, panadería, charcutería y licores. Acepta tarjetas, pago móvil y dólares.',
    consejo: 'La sede de Costa Azul es la más cómoda si te alojas en Pampatar o Costa Azul. Después de las 7 de la tarde hay menos cola.', mejorMomento: 'Mañana o después de las 19', duracion: '', costo: '' },
  { nombre: 'Río Supermarket', categoria: 'supermercado', busqueda: 'Rio Supermarket Porlamar', municipio: 'Mariño',
    descripcion: 'Supermercado grande y bien surtido en Porlamar, con sede también en el Sambil. Buena sección de frutas, quesos y productos importados.',
    consejo: 'Para una compra grande al llegar, es la mejor relación surtido-precio. Pide factura si pagas en dólares: te dan el vuelto en bolívares a la tasa del día.', mejorMomento: 'Mañana', duracion: '', costo: '' },
  { nombre: 'Al Costo Market', categoria: 'supermercado', busqueda: 'Al Costo Market Margarita', instagram: 'alcostomgta', municipio: 'Mariño',
    descripcion: 'Mercado de precios bajos muy activo en Instagram: publican ofertas cada semana. Productos básicos, limpieza y bebidas.',
    consejo: 'Revisa su Instagram antes de ir: las ofertas de quincena valen la pena para una estadía larga.', mejorMomento: 'Quincena', duracion: '', costo: '' },
  { nombre: 'Guuao Marketplace', categoria: 'licores', categoriasExtra: ['nocturna'], busqueda: 'GUUAO MARKETPLACE MARGARITA', municipio: 'Maneiro',
    descripcion: 'Bodegón y licorería con terraza: de día compras ron, vino y cerveza importada a buen precio; de noche es punto de encuentro para tomar algo con música hasta la medianoche. Estacionamiento propio.',
    consejo: 'Si quieres llevarte ron de regalo, aquí está la mejor selección de Santa Teresa, Diplomático y Pampero. Para la noche, llega antes de las 10: cierra a las 12.', mejorMomento: 'Tarde-noche', duracion: '', costo: '$$' },
  { nombre: 'Prolicor', categoria: 'licores', busqueda: 'Prolicor Porlamar', municipio: 'Mariño',
    descripcion: 'Licorería clásica de Porlamar con dos sedes: precios de mayorista, cerveza fría por cajas y todo el ron nacional.',
    consejo: 'Para una reunión en el apartamento, la caja de cerveza sale más barata acá que en el supermercado.', mejorMomento: '', duracion: '', costo: '' },
  { nombre: 'El Abuelo Pachanguero — licores a domicilio', categoria: 'licores', busqueda: '', instagram: 'elabuelopachangueromgta', municipio: 'Mariño', direccion: 'Delivery en Porlamar, Pampatar y Costa Azul',
    descripcion: 'Licorería con delivery en Porlamar, Pampatar y Costa Azul: pides por Instagram o WhatsApp y te lo llevan al apartamento, con hielo.',
    consejo: 'Pide antes de las 9 de la noche los fines de semana; después se satura. Pregunta si tienen hielo y vasos.', mejorMomento: 'Tarde', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Pizzería El Paseo — delivery', categoria: 'delivery', busqueda: 'Pizzeria El Paseo Porlamar', municipio: 'Mariño',
    descripcion: 'Una de las pizzerías más pedidas de la isla, con delivery propio en Porlamar, Costa Azul y Pampatar.',
    consejo: 'Los viernes y sábados demora más de una hora: pide temprano.', mejorMomento: 'Noche', duracion: '', costo: 'Delivery según zona' },
  { nombre: "Bro's Venezuela — hamburguesas", categoria: 'delivery', busqueda: "Bro's Venezuela Snack Burger Margarita", municipio: 'Mariño',
    descripcion: 'Hamburguesas y snacks con delivery, de los más reseñados de Porlamar.',
    consejo: 'Pide por WhatsApp directo: suele ser más rápido que por apps.', mejorMomento: 'Noche', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'TequeDun — tequeños y pasapalos', categoria: 'delivery', busqueda: '', instagram: 'tequedun', municipio: 'Mariño', direccion: 'Delivery en Porlamar y alrededores',
    descripcion: 'Tequeños, pasapalos y bandejas para compartir, a domicilio. Lo venezolano para una tarde de playa en el apartamento.',
    consejo: 'Ideal para la llegada: pides desde el aeropuerto y comes al entrar. Encarga con unas horas.', mejorMomento: 'Tarde', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Yummy — delivery y transporte', categoria: 'delivery', busqueda: '', web: 'https://yummysuperapp.com/', municipio: '', direccion: 'App · Porlamar, Pampatar, Costa Azul',
    descripcion: 'La app venezolana de delivery de comida, mercado y farmacia, que además pide carros (Yummy Rides). Funciona en Porlamar, Pampatar y Costa Azul. Se paga con tarjeta internacional, pago móvil o efectivo.',
    consejo: 'Descárgala antes de viajar y registra tu tarjeta: es la forma más fácil de pedir comida y moverte sin efectivo.', mejorMomento: '', duracion: '', costo: 'Según pedido' },
  { nombre: 'Agua La Fuente — botellones a domicilio', categoria: 'agua', busqueda: 'Agua la Fuente Margarita', municipio: 'Mariño',
    descripcion: 'Agua potable en botellones de 19 litros con entrega a domicilio en Porlamar, Pampatar y Costa Azul. La mejor valorada de la isla.',
    consejo: 'Pide el botellón con dispensador al llegar: el agua del grifo en la isla no es para tomar. Guarda el envase, se cambia por uno lleno.', mejorMomento: 'Mañana', duracion: '', costo: 'Botellón + depósito del envase' },
  { nombre: 'Freskagua', categoria: 'agua', busqueda: 'Freskagua Margarita', municipio: 'Mariño',
    descripcion: 'Agua purificada en botellones y bolsas, con delivery. Alternativa cuando La Fuente no llega a tu zona.',
    consejo: 'Pregunta el horario de reparto de tu zona: suelen tener días fijos.', mejorMomento: '', duracion: '', costo: 'Botellón' },
  { nombre: 'Tu Cisterna Margarita — camión de agua', categoria: 'agua', busqueda: '', instagram: 'tucisternamargarita', municipio: '', direccion: 'Toda la isla', web: 'http://wa.link/n680oh',
    descripcion: 'Camión cisterna para llenar el tanque de la casa o del edificio cuando el agua por tubería no llega. Es un servicio normal en la isla, no una emergencia.',
    consejo: 'Esto lo coordina el anfitrión, no el huésped: si notas que el tanque baja, avísanos por WhatsApp y nosotros lo pedimos.', mejorMomento: '', duracion: '', costo: 'Por viaje' },
  { nombre: 'Servibombas Margarita — gas', categoria: 'agua', busqueda: 'Servibombas Margarita gas', municipio: 'Mariño',
    descripcion: 'Recarga y cambio de bombonas de gas doméstico con entrega.',
    consejo: 'Igual que el agua: si se acaba el gas, escríbenos y lo resolvemos nosotros. No manipules la bombona.', mejorMomento: '', duracion: '', costo: 'Por bombona' },
  { nombre: 'Farmatodo', categoria: 'salud', busqueda: 'Farmatodo Porlamar', municipio: 'Mariño',
    descripcion: 'Farmacia grande tipo autoservicio, con medicinas, cuidado personal, bebés y algo de mercado. Varias sedes; algunas abren 24 horas.',
    consejo: 'Para protector solar, repelente y analgésicos es la opción más fácil. Aceptan tarjeta internacional.', mejorMomento: '', duracion: '', costo: '' },
  { nombre: 'Farmacia El Crucero', categoria: 'salud', busqueda: 'Farmacia El Crucero Margarita', instagram: 'farmaciaelcrucero.mgta', municipio: 'Mariño',
    descripcion: 'Farmacia de barrio activa en Instagram, con delivery de medicinas y atención por WhatsApp.',
    consejo: 'Si necesitas una medicina con receta y no quieres salir, escribiles: mandan a domicilio.', mejorMomento: '', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Hospital Clínicas del Este', categoria: 'salud', busqueda: 'Hospital Clínicas del Este Porlamar', municipio: 'Mariño',
    descripcion: 'Clínica privada con emergencias 24 horas en Porlamar. De referencia para turistas y seguros de viaje.',
    consejo: 'Guarda el número antes de necesitarlo. Emergencias nacionales: 911. Para una consulta menor, primero pregúntanos: te orientamos.', mejorMomento: '', duracion: '', costo: 'Privada' },
  { nombre: 'Centro Clínico del Caribe', categoria: 'salud', busqueda: 'Centro Clínico del Caribe Porlamar', municipio: 'Mariño',
    descripcion: 'Clínica privada en Porlamar con emergencias, laboratorio e imágenes.',
    consejo: 'Lleva pasaporte o cédula y, si tienes seguro de viaje, el número de póliza.', mejorMomento: '', duracion: '', costo: 'Privada' },
  { nombre: 'Ridery — carros por app', categoria: 'transporte', busqueda: '', web: 'https://ridery.app/', municipio: '', direccion: 'App · Porlamar, Pampatar, Costa Azul y aeropuerto',
    descripcion: 'La app de transporte más usada en Venezuela, con cobertura en Porlamar, Pampatar, Costa Azul y aeropuerto. Precio fijo antes de subir, pago con tarjeta o efectivo.',
    consejo: 'Es la forma más segura de moverte de noche. Registra la tarjeta antes de viajar; con datos móviles funciona sin problema.', mejorMomento: '', duracion: '', costo: 'Según trayecto' },
  { nombre: 'Central Taxi Costa Azul', categoria: 'transporte', busqueda: 'Central Taxi Costa Azul Margarita', municipio: 'Mariño',
    descripcion: 'Línea de taxis de Costa Azul, la zona hotelera. Atienden por teléfono y WhatsApp, también al aeropuerto.',
    consejo: 'Acuerda el precio antes de subir. Del aeropuerto a Costa Azul son unos 20 minutos.', mejorMomento: '', duracion: '', costo: 'Según trayecto' },
  { nombre: 'DG Automóviles — alquiler de carros', categoria: 'transporte', busqueda: 'Dg Automoviles Car Rental Margarita', municipio: 'Mariño',
    descripcion: 'La agencia de alquiler de carros mejor valorada de la isla, con entrega en el aeropuerto y en el alojamiento.',
    consejo: 'Para ir a Macanao, La Restinga o Punta Arenas conviene carro. Reserva con días de anticipación en temporada.', mejorMomento: '', duracion: '', costo: 'Por día' },
  { nombre: 'Traslados y autos de Margarita Renace', categoria: 'transporte', busqueda: '', web: 'https://margaritarenace.com.ve/autos', municipio: '', telefono: '+58 424 1161238', direccion: 'Aeropuerto Santiago Mariño, ferry y toda la isla',
    descripcion: 'Nuestro propio traslado desde el aeropuerto Santiago Mariño o el ferry hasta tu alojamiento, y alquiler de carros. Precio cerrado por WhatsApp antes de viajar.',
    consejo: 'Escríbenos con tu hora de llegada y te esperamos con el nombre en un cartel. Sin regatear a la salida del aeropuerto.', mejorMomento: '', duracion: '', costo: 'Precio cerrado por WhatsApp' },
  // ── Descubiertos en Instagram con Apify (2026-09-13) ──
  { nombre: 'El Empanadazo Margariteño', categoria: 'comer', busqueda: 'El Empanadazo Margariteño Playa La Caracola Porlamar', instagram: 'elempanadazo.mgta', web: 'https://elempanadazo.ola.click/', municipio: 'Mariño',
    descripcion: 'El desayuno margariteño por excelencia: empanadas de cazón, arepas y jugos naturales frente a Playa La Caracola, en Porlamar. La cuenta de Instagram con más seguidores de la isla en comida (casi 30 mil).',
    consejo: 'Abre de jueves a lunes, de 7 de la mañana a 1 de la tarde. Pide la de cazón con ají dulce y llega antes de las 9 los fines de semana.', mejorMomento: 'Desayuno', duracion: '1 hora', costo: '$' },
  { nombre: 'El Rey de las Empanadas — delivery', categoria: 'delivery', busqueda: 'El Rey de las Empanadas Pampatar', instagram: 'elreydelasempanadasmgta', web: 'https://wa.link/p8p9fj', municipio: 'Maneiro', direccion: 'Pampatar · delivery',
    descripcion: 'Empanadas venezolanas todos los días de 7 de la mañana a 2 de la tarde, con delivery en Pampatar y alrededores. Pedido por WhatsApp.',
    consejo: 'Para el desayuno del primer día: pide la noche anterior por WhatsApp y te llegan calientes al apartamento.', mejorMomento: 'Desayuno', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Zaituzaatar — comida árabe a domicilio', categoria: 'delivery', busqueda: '', instagram: 'zaituzaatar', web: 'https://wa.link/sk4kgr', municipio: 'Mariño', direccion: 'Delivery en toda la zona de Porlamar y Pampatar',
    descripcion: 'Comida árabe casera (shawarma, kibbe, falafel, tabule) con delivery y catering. Margarita tiene una comunidad árabe grande y esta es de las cocinas más seguidas.',
    consejo: 'La bandeja mixta rinde para 3 o 4 personas. Encarga con una hora de anticipación.', mejorMomento: 'Almuerzo o cena', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Taste — pollo broaster, alitas y pizzas', categoria: 'delivery', busqueda: '', instagram: 'taste.mgta', telefono: '+58 412 3939617', municipio: 'García', direccion: 'Villa Rosa · delivery',
    descripcion: 'Pollo broaster, alitas y pizzas con delivery desde Villa Rosa. De miércoles a lunes, de 1 a 9 de la noche.',
    consejo: 'Buena opción para una noche de piscina con niños: pide por WhatsApp directo.', mejorMomento: 'Noche', duracion: '', costo: 'Delivery según zona' },
  { nombre: 'Tu Regalo Margarita — desayunos sorpresa', categoria: 'delivery', busqueda: '', instagram: 'turegalo.mgta', telefono: '+58 412 4654621', municipio: 'Mariño', direccion: 'Delivery a toda la isla',
    descripcion: 'Desayunos sorpresa, flores y regalos con delivery a toda la isla. Más de 13 mil seguidores en Instagram.',
    consejo: 'Si vienes a celebrar algo (cumpleaños, aniversario), encarga el desayuno con un día de anticipación y te lo llevan al apartamento.', mejorMomento: 'Mañana', duracion: '', costo: 'Según pedido' },
  { nombre: 'Rosita Cocina', categoria: 'comer', busqueda: 'Rosita Cocina Restaurante Calle Marcano Porlamar', instagram: 'rositacocina', municipio: 'Mariño',
    descripcion: 'Cocina con calor de hogar: de Cartagena a Margarita. Desayunos y almuerzos criollos y caribeños en la calle Marcano de Porlamar, con más de 15 mil seguidores.',
    consejo: 'Lunes a viernes de 7:30 a 3; sábado y domingo solo hasta la 1. Los desayunos del fin de semana se llenan: ve temprano.', mejorMomento: 'Desayuno o almuerzo', duracion: '1 hora', costo: '$$' },
  { nombre: 'Agua Light — recarga de botellones', categoria: 'agua', busqueda: 'Agua Light recarga agua Playa el Angel Margarita', instagram: 'agualightmgta', telefono: '+58 412 3576067', municipio: 'Maneiro', direccion: 'Av. Aldonza Manrique, Playa El Ángel · delivery',
    descripcion: 'Recarga de agua purificada en botellones con delivery, desde Playa El Ángel (entre Pampatar y Porlamar). Atienden por WhatsApp.',
    consejo: 'Si te quedas en Pampatar o Costa Azul, es la más cercana. Pide la recarga por WhatsApp y ten el botellón vacío listo para el cambio.', mejorMomento: 'Mañana', duracion: '', costo: 'Botellón' },
  { nombre: 'Servi Aqua Margarita — cisterna', categoria: 'agua', busqueda: '', instagram: 'serviaquamgta', web: 'https://wa.link/u3r8zo', municipio: '', direccion: 'Toda la isla',
    descripcion: 'Agua por camión cisterna para tanques residenciales y comerciales. Alternativa a Tu Cisterna Margarita.',
    consejo: 'Lo coordina el anfitrión. Si el edificio se queda sin agua, escríbenos y lo pedimos nosotros.', mejorMomento: '', duracion: '', costo: 'Por viaje' },
  { nombre: 'Agua Potable Margarita — cisterna 24 h', categoria: 'agua', busqueda: '', instagram: 'aguapotablemargarita', telefono: '+58 424 8530800', municipio: '', direccion: 'Toda la isla · 24 horas',
    descripcion: 'Suministro de agua potable por cisterna, atienden las 24 horas.',
    consejo: 'Para emergencias fuera de horario. Avísanos primero: casi siempre lo resolvemos nosotros sin costo para ti.', mejorMomento: '', duracion: '', costo: 'Por viaje' },
  // ── Aliados (trato directo con Margarita Renace) ──
  { nombre: 'Caribest Water — agua a domicilio', categoria: 'agua', busqueda: 'Caribest Water recarga botellones Pampatar', instagram: 'caribest_water', telefono: '+58 412 5908351', web: 'http://wa.me/584125908351', municipio: 'Maneiro', direccion: 'Pampatar, Terranova y Jorge Coll · delivery', aliado: true,
    descripcion: 'Agua purificada por ósmosis inversa, en botellones con delivery en Pampatar, Terranova y Jorge Coll. Es la que usamos en nuestros apartamentos.',
    consejo: 'Al llegar, pide el primer botellón por WhatsApp y di que vienes de Margarita Renace. Guarda el envase vacío: se cambia por uno lleno.', mejorMomento: 'Mañana', duracion: '', costo: 'Botellón + depósito del envase' },
  { nombre: 'Ketchup Hot — empanadas y pasteles', categoria: 'delivery', busqueda: 'Ketchup Hot Empanadas Pasteles Margarita', instagram: 'ketchuphot', telefono: '+58 424 8035629', web: 'http://wa.me/584248035629', municipio: 'Mariño', direccion: 'Porlamar · delivery y pick up', aliado: true,
    descripcion: 'Empanadas y pasteles con sabor andino y oriental, casi 17 mil seguidores. Martes a viernes de 7:15 a 2; sábados y domingos hasta las 3. Delivery o para recoger.',
    consejo: 'El desayuno de fin de semana que recomendamos a todos nuestros huéspedes: pide por WhatsApp desde temprano, se agotan.', mejorMomento: 'Desayuno', duracion: '', costo: 'Delivery según zona' },
  // ── Aventura: operadores encontrados en Instagram ──
  { nombre: 'Senderos Margarita — rutas y camping', categoria: 'aventura', busqueda: '', instagram: 'senderosmargarita', web: 'https://bit.ly/WhatsAppSenderosMargarita', municipio: '', direccion: 'Salidas desde Porlamar · toda la isla',
    descripcion: 'El operador de senderismo más grande de la isla: más de 56 rutas, full days y camping, y Premio Nacional de Turismo 2024. Cerros, cuevas, playas escondidas y la península de Macanao.',
    consejo: 'Reserva por WhatsApp con días de anticipación; las salidas de fin de semana se llenan. Lleva 2 litros de agua, gorra y zapatos cerrados.', mejorMomento: 'Amanecer', duracion: 'Medio día o día completo', costo: 'Por persona, según ruta' },
  { nombre: 'Explora Margarita — senderismo y rápel', categoria: 'aventura', busqueda: 'Explora Margarita rutas senderismo', instagram: 'exploramargarita', telefono: '+58 412 3533291', web: 'https://wa.me/584123533291', municipio: '', direccion: 'Salidas desde Porlamar · toda la isla',
    descripcion: 'Más de 20 rutas de aventura: senderismo, rápel, acampadas y city tours por la historia de la isla. Más de 43 mil seguidores.',
    consejo: 'Si es tu primera vez en la montaña, pide una ruta nivel 1. Para rápel confirman con un día de anticipación.', mejorMomento: 'Amanecer', duracion: 'Medio día', costo: 'Por persona, según ruta' },
  { nombre: 'Espartanos Trekking — guías certificados', categoria: 'aventura', busqueda: '', instagram: 'espartanostrekkingmgta', web: 'http://bit.ly/EspartanosTrekking', municipio: '', direccion: 'Salidas desde La Asunción y Porlamar',
    descripcion: 'Guías certificados (RTN 23852) para montañas, playas y cuevas de la isla. Grupos pequeños y salidas frecuentes al Matasiete y al Copey.',
    consejo: 'Son los que recomendamos para el Cerro Matasiete: pregunta por la próxima salida en grupo.', mejorMomento: 'Amanecer', duracion: 'Medio día', costo: 'Por persona' },
  { nombre: 'Margarita La Perla del Caribe — excursiones', categoria: 'aventura', busqueda: '', instagram: 'margaritalaperladelcaribe', web: 'https://wa.link/l5xh16', municipio: '', direccion: 'Cabo Negro, Carecare y toda la isla',
    descripcion: 'Senderismo, rutas y paseos por rincones menos conocidos: Cabo Negro, Carecare y la costa norte. Más de 10 mil seguidores.',
    consejo: 'Buena alternativa cuando Senderos Margarita está lleno. Escríbeles por WhatsApp con la fecha que tienes libre.', mejorMomento: 'Mañana', duracion: 'Medio día', costo: 'Por persona' },
  // ── Aliados encontrados en Google Places + Instagram (2026-09-13) ──
  { nombre: 'V2 Aventuras — e-bikes, jeeps y trekking', categoria: 'aventura', busqueda: 'V2Aventuras Porlamar', instagram: 'v2aventuras', telefono: '+58 414 2016635', web: 'https://www.v2aventuras.com.ve/', municipio: 'Mariño', direccion: 'Frente al C.C. La Vela, Porlamar', aliado: true, categoriasExtra: ['transporte'],
    descripcion: 'Alquiler de bicicletas eléctricas y recorridos guiados en jeep, cuatrimoto, e-bike y a pie por la Margarita que no sale en las postales: Macanao, salinas, pueblos de pescadores. Casi 14 mil seguidores.',
    consejo: 'Son nuestros aliados para moverte distinto: dinos qué día tienes libre y te coordinamos la salida. La ruta en e-bike al atardecer por Pampatar es la que más recomendamos.', mejorMomento: 'Mañana temprano o atardecer', duracion: '2 horas a día completo', costo: 'Por persona, según ruta' },
  { nombre: 'Recargas La Perla — agua potable', categoria: 'agua', busqueda: 'Recargas la Perla C.A Pampatar', instagram: 'recargaslaperla', telefono: '+58 412 5860310', web: 'https://api.whatsapp.com/send?phone=584125860310', municipio: 'Maneiro', direccion: 'C.C. Paseo, nivel PB, local A-6, Av. Bolívar, Pampatar · reparto', aliado: true,
    descripcion: 'Recarga y venta de botellones de agua potable con reparto a domicilio. Lunes a sábado de 8:30 a 6:30. Es a quien llamamos nosotros.',
    consejo: 'Pide por WhatsApp y di que vienes de Margarita Renace. Si el botellón del apartamento está vacío al llegar, avísanos y lo resolvemos.', mejorMomento: 'Mañana', duracion: '', costo: 'Botellón' },
  // ── Prácticos ──
  { nombre: 'Lavandería San Jorge', categoria: 'practico', busqueda: 'Lavanderia San Jorge Jorge Coll Margarita', instagram: 'lavanderiasanjorge', telefono: '+58 424 8874344', web: 'https://wa.me/+584248874344', municipio: 'Maneiro', direccion: 'Urb. Jorge Coll · delivery',
    descripcion: 'Más de 20 años: lavandería, tintorería y costura con delivery. Lunes a viernes de 8 a 6, sábados hasta la 1.',
    consejo: 'Para una estadía larga: mándales la ropa por delivery el lunes y la tienes el miércoles. Cobran por kilo.', mejorMomento: '', duracion: '', costo: 'Por kilo' },
  { nombre: 'Lavandería La Caracola', categoria: 'practico', busqueda: 'Lavandería y tintorería la caracola Central Margarita Porlamar', municipio: 'Mariño',
    descripcion: 'Lavandería y tintorería en el C.C. Central Margarita (Av. Bolívar, Porlamar), la mejor valorada de la ciudad.',
    consejo: 'Cómoda si te quedas en Porlamar: dejas la ropa mientras haces mercado en el Central Madeirense.', mejorMomento: '', duracion: '', costo: 'Por kilo' },
  { nombre: 'Italcambio — cambio de divisas', categoria: 'practico', busqueda: 'Italcambio Centro Sambil Pampatar', instagram: 'italcambio', municipio: 'Maneiro',
    descripcion: 'Casa de cambio autorizada dentro del Sambil. Cambia dólares y euros a bolívares a la tasa oficial del día.',
    consejo: 'Casi todo se paga en dólares en efectivo o con pago móvil; solo necesitas bolívares para transporte público y algunos puestos. Cambia poco.', mejorMomento: '', duracion: '', costo: 'Comisión según monto' },
  { nombre: 'Digitel y Movistar en el Sambil — SIM y datos', categoria: 'practico', busqueda: '', municipio: 'Maneiro',
    descripcion: 'Tiendas de las operadoras en el Sambil para comprar una línea prepago venezolana con datos. Digitel suele tener mejor cobertura en la isla.',
    consejo: 'Lleva el pasaporte. Con 10 dólares tienes datos para la semana; el Wi-Fi del apartamento cubre el resto.', mejorMomento: '', duracion: '30 minutos', costo: 'Desde US$5' },
];

export const CONSEJOS: { tema: string; titulo: string; texto: string }[] = [
  { tema: 'dinero', titulo: 'Dólares, bolívares y cómo pagar', texto: 'Casi todo se cobra en bolívares a la tasa del día, aunque los precios se piensen en dólares. Trae dólares en billetes chicos (1, 5, 10, 20) en buen estado: los rotos o escritos no los aceptan. Muchos comercios aceptan pago móvil, Zelle o Binance. Para cambiar, pregunta en tu alojamiento antes que en la calle. Los cajeros dan muy poco efectivo: no cuentes con ellos.' },
  { tema: 'transporte', titulo: 'Moverse por la isla', texto: 'Hay taxis, apps como Ridery y Yummy, y los autobuses "rojitas" que cubren casi toda la isla por muy poco. Para Macanao, La Restinga o Punta Arenas conviene carro propio o traslado contratado: el transporte público es escaso. Del aeropuerto a Porlamar son 15–20 minutos; a Pampatar, 25–30. Acuerda el precio del taxi antes de subir.' },
  { tema: 'seguridad', titulo: 'Seguridad, sin dramas y sin descuidos', texto: 'Las zonas turísticas (Pampatar, Costa Azul, Playa El Agua, El Yaque) son tranquilas y con presencia policial. Lo básico: no muestres el teléfono ni joyas en la calle, no camines solo de noche por zonas que no conoces, usa taxi o app después de las 9, y no dejes cosas en la arena mientras te bañas. Si alguien te ofrece "el mejor cambio" en la calle, di no.' },
  { tema: 'playa', titulo: 'Sol, mar y corrientes', texto: 'El sol acá quema en 20 minutos: protector alto, sombrero y agua. Entre las 12 y las 3 busca sombra. Las playas del norte y del este (El Agua, Parguito, Guacuco) tienen oleaje y corrientes: báñate donde haya gente y salvavidas. Las del sur (El Yaque, Pampatar) son calmas. En temporada de lluvias (junio a noviembre) hay aguaceros cortos, después vuelve el sol.' },
  { tema: 'comida', titulo: 'Qué comer', texto: 'Pescado frito con tostones o arepitas dulces en cualquier kiosco de playa es la comida de la isla. Empanadas de cazón en la mañana, pastel de chucho, ensalada de pepitonas, y el sancocho de pescado los domingos. Toma agua embotellada o filtrada; el hielo de los restaurantes establecidos es seguro.' },
  { tema: 'temporadas', titulo: 'Cuándo venir', texto: 'Temporada alta: Carnaval, Semana Santa, agosto y del 20 de diciembre al 6 de enero — más gente, más precio, más ambiente. Mayo, junio y de septiembre a noviembre son los meses más tranquilos y más baratos. El viento para kite es más constante de diciembre a julio.' },
  { tema: 'servicios', titulo: 'Agua, luz e internet', texto: 'Es normal que el agua llegue por tanque o cisterna y que haya cortes de luz cortos: los buenos alojamientos tienen tanque y planta. El internet móvil funciona bien en las zonas turísticas con Digitel o Movistar; compra una SIM local si te quedas varios días. Descarga los mapas de Google sin conexión antes de salir a Macanao.' },
];
